### ISSUE TITLE
Wordpress local setup using docker

### ISSUE THREAD

**Issue by wasifmunir** [WITPASS/example-wordpress-website#1]
[Docker local setup Queries.pdf](https://github.com/WITPASS/example-wordpress-website/files/3022155/Docker.local.setup.Queries.pdf)

**Comment by KamranAzeem** [comment]
Wa-alaikum-us-salam Wasif sb,
Please note this is a public repository , and anything you upload in this repository will be publicly visible / accessible. The pdf file you have attached has your personal github token in it. So, first thing you should do is delete the git token from your github account, and create another one, and this time please check that the code you upload does not contain anything sensitive. 

Also, please put in text directly in the github issue, because it is not possible to write a response without able to look at it. (Switching between a PDF and this window is painful). This also does not serve documentation. You can upload/add screenshots  to an issue - that is not a problem. Just make sure the screenshots do not contain anything sensitive.

Your questions and their answers:

> Setup a MySQL database to hold this site's database stuff, and/or keep the DB credentials handy.

> Where will be setup this database? Locally?
> I have xampp on my local server which is providing mysql.

Yes, for now you set it up locally. I do not know XAMPP, but I guess that you can reach it from the container by using the IP address of the docker0 interface (or whatever it is called in windows). Here is how the networking looks like at least on Linux.
```
[your computer / docker host](docker0: 172.17.0.1)----------(eth0:172.17.0.7)[wordpress-container]
```
The dbname, dbuser and dbpassword will be the ones you have already created in your mysql instance.


> Upload folder 

Seems ok. Though from file-management perspective, it would be much better to use something like: `C:\DockerProjects\example.com\uploads` . :) 

> This command did not run and it says it it not present locally
> `docker-compose -f docker-compose.localpc build`

Yes. Sorry, error in documentation. It should be:
```
docker-compose -f docker-compose.yml.localpc build
```
and
```
docker-compose -f docker-compose.yml.localpc up -d 
```

> It was referring to port 80 which was already being used by IIS server on my PC. It was giving error there so i changed it to some other port name.

Good. This is very much configurable in `docker-compose.yml.localpc` .

> Then it has nothing on port localhost:1085

I need to see your `docker-compose.yml.localpc` file. Rather, you can fix this by adjusting the `ports:` section like so: 
```
    # Enable ports directive only on your local work computer.
    ports:
      - 1085:80
```

> After build my working directory is still the same

Yes. It should remain same. You should not expect any build-artifacts popping up in the directory :)

> Container not starting - mysql errors

Change `app.env` file to have actual values according to the setup you have on your local pc. 
```
WORDPRESS_DB_HOST=172.17.0.1
WORDPRESS_DB_NAME=db_example_com
WORDPRESS_DB_USER=user_example_com
WORDPRESS_DB_PASSWORD=secretpassword
WORDPRESS_TABLE_PREFIX=wp_
APACHE_RUN_USER=#1000
APACHE_RUN_GROUP=#1000
GITHUB_USER=kamran
GITHUB_TOKEN=base64encodedgithubtoken
```
I have absolutely zero idea how would you find the **id** of the **windows user** , and then pass it to docker. You need this information so you can setup APACHE_RUN_USER and APACHE_RUN_GROUP . But, for now, your main objective should be to get the container up, and be able to reach it from your browser on the port you choose. i.e. comment out the volume section for now in docker-compose.yml-localpc file. When you have it up and running, see if you can mount the volume correctly, and that you are actually able to create a test blog post with some picture in it and it gets saved in your persistent storage.

**Comment by KamranAzeem** [comment]
Since this developer is no more with us, I am closing this issue.
